#!/bin/bash

### BEGIN INIT INFO
# Provides:          ec2-run-user-data
# Required-Start:    $network $local_fs $remote_fs $syslog $all
# Required-Stop:     
# Default-Start:     2 3 4 5
# Default-Stop:      
# Short-Description: Run EC2 user-data scripts
# Description:       On first boot of EC2 instance, runs user-data if it starts with #!
#
### END INIT INFO

# ec2-run-user-data - Run instance user-data if it looks like a script.
#
# Only retrieves and runs the user-data script once per instance.  If
# you want the user-data script to run again (e.g., on the next boot)
# then add this command in the user-data script:
#   rm -f /var/ec2/ec2-run-user-data.*
#
# History:
#
#   2011-03-25 Eric Hammond <ehammond@thinksome.com>
#   - Add LSB info to support update-rc.d
#   - Improve check for compressed user-data
#
#   2010-01-07 Tom White
#   - Add support for gzip-compressed user data
#
#   2008-05-16 Eric Hammond <ehammond@thinksome.com>
#   - Initial version including code from Kim Scheibel, Jorge Oliveira
#

prog=$(basename $0)
curl="curl --retry 3 --silent --show-error --fail"
instance_data_url=http://169.254.169.254/2008-02-01

# Exit if we have already run on this instance (e.g., previous boot).
ami_id=$($curl $instance_data_url/meta-data/ami-id)
been_run_file=/var/ec2/$prog.$ami_id
mkdir -p $(dirname $been_run_file)
if [ -f $been_run_file ]; then
  cat $been_run_file
  exit
fi

# Retrieve the instance user-data and run it if it looks like a script
user_data_file=/tmp/ec2-user-data
echo "Retrieving user-data"
$curl -o $user_data_file $instance_data_url/user-data
if [ "$(file -bi $user_data_file| cut -f1 -d';')" = 'application/x-gzip' ]; then
  echo "Uncompressing gzip'd user-data"
  mv $user_data_file $user_data_file.gz
  gunzip $user_data_file.gz
fi
if [ ! -s $user_data_file ]; then
  echo "No user-data available"
  echo "user-data was not available" > $been_run_file
elif head -1 $user_data_file | egrep -v '^#!'; then
  echo "Skipping user-data as it does not begin with #!"
  echo "user-data did not begin with #!" > $been_run_file
else
  echo "Running user-data"
  echo "user-data has already been run on this instance" > $been_run_file
  echo "====="
  chmod +x $user_data_file
  $user_data_file
  echo "====="
  echo "user-data exit code: $?"
fi
rm -f $user_data_file
