#!/bin/bash

### BEGIN INIT INFO
# Provides:          ephemeral123-raid
# Required-Start:    $local_fs $syslog $all
# Required-Stop:     
# Default-Start:     2 3 4 5
# Default-Stop:      
# Short-Description: Mount ephemeral(1,2,3) as a big RAID0
# Description:       Mount ephemeral(1,2,3) as a big RAID0
#
### END INIT INFO

DEVS=""
devcount=0

for dev in $(curl -fsS http://169.254.169.254/latest/meta-data/block-device-mapping/ | egrep ephemeral[^0])
do
  DEVICE=/dev/$(curl -fsS http://169.254.169.254/latest/meta-data/block-device-mapping/$dev)
  DEVS="$DEVS $DEVICE"
  devcount=$((devcount+1))
done

if [ $devcount -gt 0 ]; then
  echo "Enabling RAID on $DEVS"
  mdadm --create -R /dev/md0 -l 0 -n $devcount $DEVS
  mkfs.ext4 -q -O^has_journal -L ec2ephemeral /dev/md0
  mkdir -p /ephemeral
  mount -o async,noatime /dev/md0 /ephemeral
else
  echo "No ephemeral stores to RAID"
fi
