#!/bin/bash

### BEGIN INIT INFO
# Provides:          resize-filesystems
# Required-Start:    $local_fs $syslog
# Required-Stop:     
# Default-Start:     2 3 4 5
# Default-Stop:      
# Short-Description: Resize filesystems to reflect changes in EBS volume sizes
# Description:       On boot, resize filesystems to reflect changes in EBS volume sizes
#
### END INIT INFO

egrep 'ext(2|3|4)' /proc/mounts | cut -f 1 -d ' ' | while read disk
do
  resize2fs $disk &
done
